name: NexoAddon
version: ${project.version}
main: zone.vao.nexoAddon.NexoAddon
api-version: '1.20'
author: "Naimad (discord: 4g0)"
loader: zone.vao.nexoAddon.loader.NALoader
folia-supported: true
dependencies:
  server:
    Nexo:
      load: BEFORE
      required: true
      join-classpath: true
    packetevents:
      load: BEFORE
      required: false
      join-classpath: true
    MythicMobs:
      load: BEFORE
      required: false
      join-classpath: true
    CrashClaim:
      load: BEFORE
      required: false
      join-classpath: true
    HuskTowns:
      load: BEFORE
      required: false
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    Towny:
      load: BEFORE
      required: false
      join-classpath: true
    Factions:
      load: BEFORE
      required: false
      join-classpath: true
    Lands:
      load: BEFORE
      required: false
      join-classpath: true
    PlotSquared:
      load: BEFORE
      required: false
      join-classpath: true