name: NexoAddon
version: ${project.version}
main: zone.vao.nexoAddon.NexoAddon
api-version: '1.20'
author: "Naimad (discord: 4g0)"
softdepend: [ WorldGuard, Towny, Factions, Lands, PlotSquared, CrashClaim, HuskTowns, ProtocolLib ]
depend:
  - Nexo